### ISSUE TITLE
installed requirments, grunt etc and i get this

### ISSUE THREAD

**Issue by shiznewski** [scottstamp/PokemonGo-Map#3]
File "/_pkmgo/2/pogom/search.py", line 216, in search_worker_thread
    check_login(args, account, api, step_location)
  File "/_pkmgo/2/pogom/search.py", line 261, in check_login
    api.set_authentication(provider = account['auth_service'], username = account['username'], password = account['password'])
  File "/_pkmgo/2/src/pgoapi/pgoapi/pgoapi.py", line 89, in __getattr__
    raise AttributeError
AttributeError
2016-08-06 23:07:58,444 [ search_worker_0][        search][    INFO] Search step 117 beginning (queue size is 154)
2016-08-06 23:07:58,445 [ search_worker_0][        search][   ERROR] Exception in search_worker:
Traceback (most recent call last):
  File "/_pkmgo/2/pogom/search.py", line 216, in search_worker_thread
    check_login(args, account, api, step_location)
  File "/_pkmgo/2/pogom/search.py", line 261, in check_login
    api.set_authentication(provider = account['auth_service'], username = account['username'], password = account['password'])
  File "/_pkmgo/2/src/pgoapi/pgoapi/pgoapi.py", line 89, in __getattr__
    raise AttributeError

**Comment by skvvv** [comment]
This is a wild guess, but maybe try lowering step size?
It should be above 5 however.
