### ISSUE TITLE
Runserver error

### ISSUE THREAD

**Issue by IHG54** [scottstamp/PokemonGo-Map#36]
- Environment name and version Python 2.7
- Operating System and version (desktop or mobile): Windows 10

Hello, 
i have a error message for " runserver.py " 

`[      MainThread][     runserver][CRITICAL] Please run "grunt build" before starting the server`

http://prntscr.com/c2z2mv

**Comment by bspans** [comment]
checkout this thread https://github.com/scottstamp/PokemonGo-Map/issues/8 

I've fixed it by first installing NPM for windows 
next going to the folder where the runserver.py is and opening a cmd window there. 
next typing npm install 
and the Grunt build error went away

**Comment by Azryyal** [comment]
We really need push request #10 which has this information in the README.md.....

**Comment by IHG54** [comment]
Ok thank you !
I have install all but i have a new error message:

`2016-08-08 17:51:36,944 [ search_worker_0][        search][    INFO] Search step 1 beginning (queue size is 0)
2016-08-08 17:51:36,960 [ search_worker_0][   auth_google][    INFO] Google User Login for: xxx@gmail.com
2016-08-08 17:51:37,138 [ search_worker_0][        search][   ERROR] Exception in search_worker: [Errno 1] _ssl.c:504: error:14090086:SSL routines:SSL3_GET_SERVER_CERTIFICATE:certificate verify failed
Traceback (most recent call last):
  File "C:\Users\Logins-IHG\Documents\Pokemon Go Tools\Maps\Pokemon Go-Map-develop\pogom\search.py", line 216, in search_worker_thread
    check_login(args, account, api, step_location)
  File "C:\Users\Logins-IHG\Documents\Pokemon Go Tools\Maps\Pokemon Go-Map-develop\pogom\search.py", line 261, in check_login
    api.set_authentication(provider = account['auth_service'], username = account['username'], password = account['password'])
  File "C:\Python27\lib\site-packages\pgoapi-1.1.6-py2.7.egg\pgoapi\pgoapi.py", line 81, in set_authentication
    self._auth_provider.user_login(username, password)
  File "C:\Python27\lib\site-packages\pgoapi-1.1.6-py2.7.egg\pgoapi\auth_google.py", line 55, in user_login
    user_login = perform_master_login(username, password, self.GOOGLE_LOGIN_ANDROID_ID)
  File "C:\Python27\lib\site-packages\gpsoauth\__init__.py", line 66, in perform_master_login
    return _perform_auth_request(data)
  File "C:\Python27\lib\site-packages\gpsoauth\__init__.py", line 22, in _perform_auth_request
    headers={'User-Agent': useragent})
  File "C:\Python27\lib\site-packages\requests\api.py", line 111, in post
    return request('post', url, data=data, json=json, **kwargs)
  File "C:\Python27\lib\site-packages\requests\api.py", line 57, in request
    return session.request(method=method, url=url, **kwargs)
  File "C:\Python27\lib\site-packages\requests\sessions.py", line 475, in request
    resp = self.send(prep, **send_kwargs)
  File "C:\Python27\lib\site-packages\requests\sessions.py", line 585, in send
    r = adapter.send(request, **kwargs)
  File "C:\Python27\lib\site-packages\requests\adapters.py", line 477, in send
    raise SSLError(e, request=request)
SSLError: [Errno 1] _ssl.c:504: error:14090086:SSL routines:SSL3_GET_SERVER_CERTIFICATE:certificate verify failed
2016-08-08 17:51:37,181 [ search_worker_0][        search][    INFO] Search step 2 beginning (queue size is 125)
2016-08-08 17:51:37,194 [ search_worker_0][   auth_google][    INFO] Google User Login for: xxx@gmail.com
2016-08-08 17:51:37,305 [ search_worker_0][        search][   ERROR] Exception in search_worker: [Errno 1] _ssl.c:504: error:14090086:SSL routines:SSL3_GET_SERVER_CERTIFICATE:certificate verify failed
Traceback (most recent call last):
  File "C:\Users\Logins-IHG\Documents\Pokemon Go Tools\Maps\Pokemon Go-Map-develop\pogom\search.py", line 216, in search_worker_thread
    check_login(args, account, api, step_location)
  File "C:\Users\Logins-IHG\Documents\Pokemon Go Tools\Maps\Pokemon Go-Map-develop\pogom\search.py", line 261, in check_login
    api.set_authentication(provider = account['auth_service'], username = account['username'], password = account['password'])
  File "C:\Python27\lib\site-packages\pgoapi-1.1.6-py2.7.egg\pgoapi\pgoapi.py", line 81, in set_authentication
    self._auth_provider.user_login(username, password)
  File "C:\Python27\lib\site-packages\pgoapi-1.1.6-py2.7.egg\pgoapi\auth_google.py", line 55, in user_login
    user_login = perform_master_login(username, password, self.GOOGLE_LOGIN_ANDROID_ID)
  File "C:\Python27\lib\site-packages\gpsoauth\__init__.py", line 66, in perform_master_login
    return _perform_auth_request(data)
  File "C:\Python27\lib\site-packages\gpsoauth\__init__.py", line 22, in _perform_auth_request
    headers={'User-Agent': useragent})
  File "C:\Python27\lib\site-packages\requests\api.py", line 111, in post
    return request('post', url, data=data, json=json, **kwargs)
  File "C:\Python27\lib\site-packages\requests\api.py", line 57, in request
    return session.request(method=method, url=url, **kwargs)
  File "C:\Python27\lib\site-packages\requests\sessions.py", line 475, in request
    resp = self.send(prep, **send_kwargs)
  File "C:\Python27\lib\site-packages\requests\sessions.py", line 585, in send
    r = adapter.send(request, **kwargs)
  File "C:\Python27\lib\site-packages\requests\adapters.py", line 477, in send
    raise SSLError(e, request=request)
SSLError: [Errno 1] _ssl.c:504: error:14090086:SSL routines:SSL3_GET_SERVER_CERTIFICATE:certificate verify failed
2016-08-08 17:51:37,351 [ search_worker_0][        search][    INFO] Search step 3 beginning (queue size is 124)
2016-08-08 17:51:37,361 [ search_worker_0][   auth_google][    INFO] Google User Login for: xxx@gmail.com
2016-08-08 17:51:37,464 [ search_worker_0][        search][   ERROR] Exception in search_worker: [Errno 1] _ssl.c:504: error:14090086:SSL routines:SSL3_GET_SERVER_CERTIFICATE:certificate verify failed
Traceback (most recent call last):
  File "C:\Users\Logins-IHG\Documents\Pokemon Go Tools\Maps\Pokemon Go-Map-develop\pogom\search.py", line 216, in search_worker_thread
    check_login(args, account, api, step_location)
  File "C:\Users\Logins-IHG\Documents\Pokemon Go Tools\Maps\Pokemon Go-Map-develop\pogom\search.py", line 261, in check_login
    api.set_authentication(provider = account['auth_service'], username = account['username'], password = account['password'])
  File "C:\Python27\lib\site-packages\pgoapi-1.1.6-py2.7.egg\pgoapi\pgoapi.py", line 81, in set_authentication
    self._auth_provider.user_login(username, password)
  File "C:\Python27\lib\site-packages\pgoapi-1.1.6-py2.7.egg\pgoapi\auth_google.py", line 55, in user_login
    user_login = perform_master_login(username, password, self.GOOGLE_LOGIN_ANDROID_ID)
  File "C:\Python27\lib\site-packages\gpsoauth\__init__.py", line 66, in perform_master_login
    return _perform_auth_request(data)
  File "C:\Python27\lib\site-packages\gpsoauth\__init__.py", line 22, in _perform_auth_request
    headers={'User-Agent': useragent})
  File "C:\Python27\lib\site-packages\requests\api.py", line 111, in post
    return request('post', url, data=data, json=json, **kwargs)
  File "C:\Python27\lib\site-packages\requests\api.py", line 57, in request
    return session.request(method=method, url=url, **kwargs)
  File "C:\Python27\lib\site-packages\requests\sessions.py", line 475, in request
    resp = self.send(prep, **send_kwargs)
  File "C:\Python27\lib\site-packages\requests\sessions.py", line 585, in send
    r = adapter.send(request, **kwargs)
  File "C:\Python27\lib\site-packages\requests\adapters.py", line 477, in send
    raise SSLError(e, request=request)
SSLError: [Errno 1] _ssl.c:504: error:14090086:SSL routines:SSL3_GET_SERVER_CERTIFICATE:certificate verify failed
2016-08-08 17:51:37,516 [ search_worker_0][        search][    INFO] Search step 4 beginning (queue size is 123)
2016-08-08 17:51:37,525 [ search_worker_0][   auth_google][    INFO] Google User Login for: xxx@gmail.com
2016-08-08 17:51:37,640 [ search_worker_0][        search][   ERROR] Exception in search_worker: [Errno 1] _ssl.c:504: error:14090086:SSL routines:SSL3_GET_SERVER_CERTIFICATE:certificate verify failed
Traceback (most recent call last):
  File "C:\Users\Logins-IHG\Documents\Pokemon Go Tools\Maps\Pokemon Go-Map-develop\pogom\search.py", line 216, in search_worker_thread
    check_login(args, account, api, step_location)
  File "C:\Users\Logins-IHG\Documents\Pokemon Go Tools\Maps\Pokemon Go-Map-develop\pogom\search.py", line 261, in check_login
    api.set_authentication(provider = account['auth_service'], username = account['username'], password = account['password'])
  File "C:\Python27\lib\site-packages\pgoapi-1.1.6-py2.7.egg\pgoapi\pgoapi.py", line 81, in set_authentication
    self._auth_provider.user_login(username, password)
  File "C:\Python27\lib\site-packages\pgoapi-1.1.6-py2.7.egg\pgoapi\auth_google.py", line 55, in user_login
    user_login = perform_master_login(username, password, self.GOOGLE_LOGIN_ANDROID_ID)
  File "C:\Python27\lib\site-packages\gpsoauth\__init__.py", line 66, in perform_master_login
    return _perform_auth_request(data)
  File "C:\Python27\lib\site-packages\gpsoauth\__init__.py", line 22, in _perform_auth_request
    headers={'User-Agent': useragent})
  File "C:\Python27\lib\site-packages\requests\api.py", line 111, in post
    return request('post', url, data=data, json=json, **kwargs)
  File "C:\Python27\lib\site-packages\requests\api.py", line 57, in request
    return session.request(method=method, url=url, **kwargs)
  File "C:\Python27\lib\site-packages\requests\sessions.py", line 475, in request
    resp = self.send(prep, **send_kwargs)
  File "C:\Python27\lib\site-packages\requests\sessions.py", line 585, in send
    r = adapter.send(request, **kwargs)
  File "C:\Python27\lib\site-packages\requests\adapters.py", line 477, in send
    raise SSLError(e, request=request)
SSLError: [Errno 1] _ssl.c:504: error:14090086:SSL routines:SSL3_GET_SERVER_CERTIFICATE:certificate verify failed
2016-08-08 17:51:37,700 [ search_worker_0][        search][    INFO] Search step 5 beginning (queue size is 122)
2016-08-08 17:51:37,703 [ search_worker_0][   auth_google][    INFO] Google User Login for: xxx@gmail.com
2016-08-08 17:51:37,815 [ search_worker_0][        search][   ERROR] Exception in search_worker: [Errno 1] _ssl.c:504: error:14090086:SSL routines:SSL3_GET_SERVER_CERTIFICATE:certificate verify failed
Traceback (most recent call last):
  File "C:\Users\Logins-IHG\Documents\Pokemon Go Tools\Maps\Pokemon Go-Map-develop\pogom\search.py", line 216, in search_worker_thread
    check_login(args, account, api, step_location)
  File "C:\Users\Logins-IHG\Documents\Pokemon Go Tools\Maps\Pokemon Go-Map-develop\pogom\search.py", line 261, in check_login
    api.set_authentication(provider = account['auth_service'], username = account['username'], password = account['password'])
  File "C:\Python27\lib\site-packages\pgoapi-1.1.6-py2.7.egg\pgoapi\pgoapi.py", line 81, in set_authentication
    self._auth_provider.user_login(username, password)
  File "C:\Python27\lib\site-packages\pgoapi-1.1.6-py2.7.egg\pgoapi\auth_google.py", line 55, in user_login
    user_login = perform_master_login(username, password, self.GOOGLE_LOGIN_ANDROID_ID)
  File "C:\Python27\lib\site-packages\gpsoauth\__init__.py", line 66, in perform_master_login
    return _perform_auth_request(data)
  File "C:\Python27\lib\site-packages\gpsoauth\__init__.py", line 22, in _perform_auth_request
    headers={'User-Agent': useragent})
  File "C:\Python27\lib\site-packages\requests\api.py", line 111, in post
    return request('post', url, data=data, json=json, **kwargs)
  File "C:\Python27\lib\site-packages\requests\api.py", line 57, in request
    return session.request(method=method, url=url, **kwargs)
  File "C:\Python27\lib\site-packages\requests\sessions.py", line 475, in request
    resp = self.send(prep, **send_kwargs)
  File "C:\Python27\lib\site-packages\requests\sessions.py", line 585, in send
    r = adapter.send(request, **kwargs)
  File "C:\Python27\lib\site-packages\requests\adapters.py", line 477, in send
    raise SSLError(e, request=request)
SSLError: [Errno 1] _ssl.c:504: error:14090086:SSL routines:SSL3_GET_SERVER_CERTIFICATE:certificate verify failed
2016-08-08 17:51:37,864 [ search_worker_0][        search][    INFO] Search step 6 beginning (queue size is 121)
2016-08-08 17:51:37,875 [ search_worker_0][   auth_google][    INFO] Google User Login for:xxx@gmail.com
`

**Comment by cheechh** [comment]
Im having the same issue as well cant seem to find the fix been on it for awhile
