### ISSUE TITLE
[ search_worker_0][        search][   ERROR] Search step 3 map parsing failed, retrying request in 2 seconds

### ISSUE THREAD

**Issue by Drambuie** [scottstamp/PokemonGo-Map#37]
When running the program I am getting the following outputed to the terminal

Traceback (most recent call last):
  File "/home/user/PokemonGo-Map/pogom/search.py", line 236, in search_worker_thread
    parsed = parse_map(response_dict, step_location)
  File "/home/user/PokemonGo-Map/pogom/models.py", line 296, in parse_map
    cells = map_dict['responses']['GET_MAP_OBJECTS']['map_cells']
KeyError: 'map_cells'
2016-08-08 12:32:37,510 [ search_worker_0][        search][   ERROR] Search step 3 map parsing failed, retrying request in 2 seconds
## Expected Behavior

Would expect not to see this and for items to appear on the map
## Current Behavior

Nothing is being displayed on the map

Any help would be appriciated

**Comment by bspans** [comment]
check out this thread https://github.com/scottstamp/PokemonGo-Map/issues/8

**Comment by bspans** [comment]
Same problem here

**Comment by bspans** [comment]
Verify account and create the charecter 
info from: https://m.reddit.com/r/pokemongodev/comments/4wje9y/pokemongomap_reborn/
