### ISSUE TITLE
Missing requirement?

### ISSUE THREAD

**Issue by Azryyal** [scottstamp/PokemonGo-Map#5]
pip install -r requirement.txt

Results ends in this:

Collecting pyproj (from LatLon==1.0.1->-r requirements.txt (line 17))
  Downloading pyproj-1.9.5.1.tar.gz (4.4MB)
    100% |################################| 4.4MB 142kB/s
    Complete output from command python setup.py egg_info:
    using bundled proj4..
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "c:\users\eol\appdata\local\temp\pip-build-eu0rhz\pyproj\setup.py", line 72, in <module>
        objects = cc.compile(['nad2bin.c', 'src/pj_malloc.c'])
      File "c:\python27\lib\distutils\msvc9compiler.py", line 473, in compile
        self.initialize()
      File "c:\python27\lib\distutils\msvc9compiler.py", line 383, in initialize
        vc_env = query_vcvarsall(VERSION, plat_spec)
      File "c:\python27\lib\site-packages\setuptools\msvc.py", line 173, in msvc9_query_vcvarsall
        return EnvironmentInfo(arch, ver).return_env()
      File "c:\python27\lib\site-packages\setuptools\msvc.py", line 1103, in return_env
        [self.VCIncludes,
      File "c:\python27\lib\site-packages\setuptools\msvc.py", line 811, in VCIncludes
        return [os.path.join(self.si.VCInstallDir, 'Include'),
      File "c:\python27\lib\site-packages\setuptools\msvc.py", line 541, in VCInstallDir
        python_vc = self.ri.lookup(reg_path, 'installdir')
      File "c:\python27\lib\site-packages\setuptools\msvc.py", line 451, in lookup
        bkey = winreg.OpenKey(hkey, key, 0, winreg.KEY_READ)
    WindowsError: [Error 2] The system cannot find the file specified

```
----------------------------------------
```

Command "python setup.py egg_info" failed with error code 1 in c:\users\eol\appdata\local\temp\pip-build-eu0rhz\pyproj\

Do we have a missing requirement?

**Comment by TULOA** [comment]
Yes: VC For Python 27 Here:
https://www.microsoft.com/en-us/download/details.aspx?id=44266

It wasnt mentioned and thats what I found out.

**Comment by Azryyal** [comment]
Thanks. That should be added to a README or the Wiki to close this out, please and thank you. :)

**Comment by TULOA** [comment]
Your welcome.

**Comment by drakbar** [comment]
You make the changes to said files that you want to see and make a pull request...

**Comment by Azryyal** [comment]
Ok. I've updated README.md and created pull request #10 . Once that is pulled in, this can be closed out.
