### ISSUE TITLE
Please run "grunt build" before starting the server

### ISSUE THREAD

**Issue by lungbubble** [scottstamp/PokemonGo-Map#8]
after running install etc and then I run the runserver.py, it errors out and tells me 
[       MainThread][          runserver][CRITICAL] Please run "grunt build" before starting the server

I type grunt build and it says "no such file or directory: 'build' "

**Comment by bol507** [comment]
type grunt  in linux

**Comment by Aidz24** [comment]
If you're on windows. Go to your main folder and open command prompt (shift right click anywhere in the folder) and select Open Command Prompt Here. then type without the quote "npm install" 

That should take care of it.

**Comment by Cammo009** [comment]
I was just about to say the same. 
http://puu.sh/qsvnS/131703f5c8.png

**Comment by Azryyal** [comment]
And if we don't have npm?

**Comment by bol507** [comment]
![image](https://cloud.githubusercontent.com/assets/19575466/17460400/887263d8-5c2a-11e6-8737-052159097da4.png)

**Comment by TULOA** [comment]
NPM is required and part of Node.js.

Should hopefully just have to install Node.js for your version of OS and then the NPM Install like stated above.

**Comment by Azryyal** [comment]
Again, it would be helpful if this were in a README or in the wiki (which is blank). Where do I get Node.js from?

**Comment by bol507** [comment]
Os?

**Comment by Cammo009** [comment]
I installed Node.js and still nothing. I also tried. `npm install npm -g`

then i did `Grunt build` and got command not found

**Comment by Azryyal** [comment]
Found it: https://nodejs.org/en/download/

**Comment by bol507** [comment]
http://gruntjs.com/

**Comment by Cammo009** [comment]
ok that got me this. http://puu.sh/qsvUZ/102f39b540.png

**Comment by MangoTheTango** [comment]
im sorry, im kinda new at this, what folder do i shift + right click in? and what is the exact command to install npm

**Comment by Cammo009** [comment]
the main folder that contains the runserver.py

**Comment by Cammo009** [comment]
Im going to retry this. https://www.youtube.com/watch?v=RJKAulPCkRI

**Comment by MangoTheTango** [comment]
alright i got the grunt build command to work, but now when i run the whole thing with google maps api and such, i get "exception while downloading map" "search step 1 area download failed"

**Comment by Cammo009** [comment]
How you get grunt build to work. Please share.

**Comment by MangoTheTango** [comment]
okay, so first i downloaded the NPM thing from https://nodejs.org/en/download/. Next i did the npm install command, and it ran something and automatically ran grunt build with it. ALSO make sure you are running your cmd as admin

**Comment by Azryyal** [comment]
Created pull request #10 to cover at least the Windows users on this thread.

**Comment by lungbubble** [comment]
downloaded NPM.  Went to runserver.py folder, typed npm install.  Nothing.  Went to nodejs folder, typed npm install...went through some stuff it all failed.  "npm ERR! install Couldn't read dependcies" etc etc, all the way down.

Turns out it wanted some json file in the main NPM folder, not the subfolder, so I just copied it.  Did npm install again, it went through quite a bit, then gave me the following:

46953 error Windows_NT 6.1.7601
46954 error argv "C:\Program Files\nodejs\node.exe" "C:\Program Files\nodejs\node_modules\npm\bin\npm-cli.js" "install"
46955 error node v4.4.7
46956 error npm  v2.15.8
46957 error code ELIFECYCLE
46958 error npm@2.15.8 prepublish: `node bin/npm-cli.js prune --prefix=. --no-global && rimraf test/*/*/node_modules && make doc-clean && make -j4 doc`
46958 error Exit status 1
46959 error Failed at the npm@2.15.8 prepublish script 'node bin/npm-cli.js prune --prefix=. --no-global && rimraf test/_/_/node_modules && make doc-clean && make -j4 doc'.
46959 error This is most likely a problem with the npm package,
46959 error not with npm itself.
46959 error Tell the author that this fails on your system:
46959 error     node bin/npm-cli.js prune --prefix=. --no-global && rimraf test/_/_/node_modules && make doc-clean && make -j4 doc
46959 error You can get information on how to open an issue for this project with:
46959 error     npm bugs npm
46959 error Or if that isn't available, you can get their info via:
46959 error
46959 error     npm owner ls npm
46959 error There is likely additional logging output above.
46960 verbose exit [ 1, true ]

**Comment by 7ESL4** [comment]
I'm stuck on running Grunt.  If I just run the javascript is says
Line:1
Char: 1
Error 'module is undefined'
Code: 800A1391
Source: Microsoft JScript runtime error

If I run npm install, I get the above error.

**Comment by lungbubble** [comment]
Can someone please help me with this grunt build stuff?  I've tried installing the npm, etc, this whole thing seems like just a mess.  Even when grunt build works, am I supposed to do it in the folder of this "grunt" thing, or in the folder of the runserver.py, and if its in the latter, do I need to type "grunt build runserver.py" or something?

**Comment by elvquant** [comment]
Had running PGM correctly before Niantic changed the API ... Want to upgrade ...

"sudo pip install --no-cache-dir -r requirements.txt" ... completely OK!

Raspbian "Linux raspberrypi 4.1.13+ #826 PREEMPT Fri Nov 13 20:13:22 GMT 2015 armv6l GNU/Linux"

$ sudo npm install -g grunt-cli
npm http GET https://registry.npmjs.org/grunt-cli

npm ERR! Error: failed to fetch from registry: grunt-cli
npm ERR!     at /usr/share/npm/lib/utils/npm-registry-client/get.js:139:12
npm ERR!     at cb (/usr/share/npm/lib/utils/npm-registry-client/request.js:31:9)
npm ERR!     at Request._callback (/usr/share/npm/lib/utils/npm-registry-client/request.js:136:18)
npm ERR!     at Request.callback (/usr/lib/nodejs/request/main.js:119:22)
npm ERR!     at Request.<anonymous> (/usr/lib/nodejs/request/main.js:212:58)
npm ERR!     at Request.emit (events.js:88:20)
npm ERR!     at ClientRequest.<anonymous> (/usr/lib/nodejs/request/main.js:412:12)
npm ERR!     at ClientRequest.g (events.js:156:14)
npm ERR!     at ClientRequest.emit (events.js:67:17)
npm ERR!     at HTTPParser.parserOnIncomingClient [as onIncoming](http.js:1256:7)
npm ERR! You may report this log at:
npm ERR!     http://bugs.debian.org/npm
npm ERR! or use
npm ERR!     reportbug --attach /home/pi/bin/PokemonGo-Map/npm-debug.log npm
npm ERR!
npm ERR! System Linux 4.1.13+
npm ERR! command "/usr/bin/nodejs" "/usr/bin/npm" "install" "-g" "grunt-cli"
npm ERR! cwd /home/pi/bin/PokemonGo-Map
npm ERR! node -v v0.6.19
npm ERR! npm -v 1.1.4
npm ERR! message failed to fetch from registry: grunt-cli
npm ERR!
npm ERR! Additional logging details can be found in:
npm ERR!     /home/pi/bin/PokemonGo-Map/npm-debug.log
npm not ok
